# Generated by Django 4.0.5 on 2023-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_artifact_color_artifact_dimensions_artifact_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='location',
            new_name='purchase_location',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='purchase_year',
            field=models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2000', max_length=50),
        ),
    ]
