# Generated by Django 4.0.5 on 2023-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_artifact_sentimental_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='sentimental_value',
            field=models.TextField(blank='True', max_length=10000),
        ),
    ]
