# Generated by Django 4.0.5 on 2023-08-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_alter_artifact_sentimental_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='function',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Finances', 'Finances'), ('Communication', 'Communication'), ('Other', 'Other')], default='Entertainment', max_length=50),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('Other', 'Other'), ('Plastic', 'Plastic'), ('Ceramic', 'Ceramic'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Porcelain', 'Porcelain')], default='Glass', max_length=50),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='price',
            field=models.CharField(blank='True', max_length=200),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='purchase_year',
            field=models.CharField(choices=[('1990', '1990'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2000', max_length=50),
        ),
    ]
